### ISSUE TITLE
Mobile Use

### ISSUE THREAD

**Issue by usvjosh** [microsoft/azurechatgpt#100]
Hello, Thank you for providing this codebase, we've just started using it and love it so far.

We have some users that'll want to use it from their mobile devices such as smart phones. The site works on these devices with small screens but is a bit hard to use. Is there any plans to make this more small mobile device friendly? 

It might be nice to be able to collapse the new chat navigation side, to get more of a full screen view of the contents of the current chat. Maybe the ability to change the size of the fonts to fit more on the screen. 

Thank you!

**Comment by oliverlabs** [comment]
@usvjosh, it's a copy of #92
