### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by dcnsakthi** [microsoft/azurechatgpt#32]
Hi, Could you please let me know if you have come across this problem and if there is a quick solution available?

<img width="916" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/17950332/2cebb32b-c57e-4eee-90e6-f03710631b78">

**Comment by thivy** [comment]
@dcnsakthi have you configured Auth? You only need to configure GitHub or Azure AD. 

or you can bring your own Auth provider https://next-auth.js.org/providers/

**Comment by dcnsakthi** [comment]
Hi @thivy, Thanks for the response. Yes, I have GitHub auth enabled configured in .env.local file.

**Comment by oliverlabs** [comment]
I am experiencing the same issue and I configured Azure AD authentication.

**Comment by akashtalole** [comment]
Facing similar issue with github oauth

**Comment by oliverlabs** [comment]
> Facing similar issue with github oauth

I'll submit a PR to make instructions clearer. A few steps are missing or just not defined clearly.

**Comment by oliverlabs** [comment]
> Facing similar issue with github oauth

I'll submit a PR to make instructions more clear. A few steps are missing or just not defined clearly.

**Comment by thivy** [comment]
> > Facing similar issue with github oauth
> 
> I'll submit a PR to make instructions clearer. A few steps are missing or just not defined clearly.

Thank you for submitting the PR! I've approved and merged it to main

**Comment by thivy** [comment]
Merged the updated documentation to main
