### ISSUE TITLE
Deployment Error by CustomDeployment from Template to Azure

### ISSUE THREAD

**Issue by RobertHoegner** [microsoft/azurechatgpt#34]
I am unfortunately getting the following error when using the one-click deployment to azure:

{"code":"DeploymentFailed","target":"/subscriptions/XXX/resourceGroups/XXXX/providers/Microsoft.Resources/deployments/resources-5stymuvr2bba2","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","target":"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Resources/deployments/resources-5stymuvr2bba2","message":"{\r\n  \"code\": \"BadRequest\",\r\n  \"message\": \"The character 'F' at index 0 is not allowed in the DatabaseAccount name\\r\\nActivityId: 6a63308f-d2c3-49ea-a9df-fd1c369b7938, Microsoft.Azure.Documents.Common/2.14.0\"\r\n}"}]}

**Comment by RobertHoegner** [comment]
the errors is related to the cosmosdb but I cant see what caused it:

<img width="693" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/49672998/5311ee41-77bf-4d6f-9305-d8e936d9149d">

**Comment by Xtrah** [comment]
```
The character 'F' at index 0 is not allowed in the DatabaseAccount name
```

What deployment name are you using?

**Comment by RobertHoegner** [comment]
solved was caused by capital letter
