### ISSUE TITLE
AAD Auth Provider stuck in sign in loop

### ISSUE THREAD

**Issue by DavidLee-Arinco** [microsoft/azurechatgpt#38]
## Describe the issue

Infra and code successfully deployed, but when using the AAD Auth Provider, it appears to get stuck in sign in loop.
Have confirmed that the AAD App Registration is successfully issuing an auth token, and what looks like to be session tokens back to next-auth but upon hitting the /chat endpoint it gets sent back to login screen

## Screenshots 📷

![image](https://github.com/microsoft/azurechatgpt/assets/49134649/0352272e-9dae-44d1-9ba2-5b9960c182a3)

![image](https://github.com/microsoft/azurechatgpt/assets/49134649/98667577-71f4-45f3-b74c-ce64808352a8)

**Comment by thivy** [comment]
@DavidLee-Arinco Could you please check the .env.local file and remove the comment next to the NEXTAUTH_URL 

It's seems to be causing the error. I will update the documentation to remove those comments 

![image](https://github.com/microsoft/azurechatgpt/assets/1764153/20e2282b-1e4a-4768-976d-ea0ba07d0f79)

**Comment by mroyster** [comment]
I had the same and fixed by adding environment variable (in Web App Config) to set NEXTAUTH_URL to point to URL. For some reason mine was missing the https at the start.

**Comment by Nettitude-MS** [comment]
Sorry, I cannot see how you have managed to fix the issue with just adding HTTPS into the App Setting for the NEXTAUTH_URL variable.

I've added this, as I am suffering with the same issue, and all I receive when browsing back to the site is a error such as the below:

![image](https://github.com/microsoft/azurechatgpt/assets/100838612/7a856221-27dc-4686-a85a-11e1f75f81b0)

If I remove the 'HTTPS://' from the variable, I get the login screen once again but the loop still occurs. 

I've checked my redirect URI and I am confident that the login attempts are completing as I can see the application successfully authenticating into my tenancy via my UPN so I think this must be a configuration setting somewhere.

**Comment by stalejohnsen** [comment]
I get the exact same issue as @Nettitude-MS

**Comment by oliverlabs** [comment]
@Nettitude-MS , your error is due to a COSMOS DB variable not being set properly.

@mroyster provided the right answer - the NEXTAUTH_URL must contain `https://`.

**Comment by PedroGuerraPT** [comment]
> @Nettitude-MS , your error is due to a COSMOS DB variable not being set properly.
> 
> as for the OPs issue, @mroyster provided the right answer - the NEXTAUTH_URL must contain `https://`.

Thanks for pointing into the right direction @oliverlabs.

The One Click Azure Deployment is creating the App Settings `AZURE_COSMOSEDB_KEY` and `AZURE_COSMOSEDB_URI` (notice the extra E letter), and the code uses the env vars `AZURE_COSMOSDB_KEY` and `AZURE_COSMOSDB_URI` as seen [here](https://github.com/microsoft/azurechatgpt/blob/6c76fb9b3239ddd751905755267115f5e9e5b0dd/src/features/common/cosmos.ts#L8C32-L8C50)

Might be worth revising the ARM Template and the environment variables reference here as well: https://github.com/microsoft/azurechatgpt/blob/6c76fb9b3239ddd751905755267115f5e9e5b0dd/README.md?plain=1#L239

**Comment by PedroGuerraPT** [comment]
> @Nettitude-MS , your error is due to a COSMOS DB variable not being set properly.
> 
> as for the OPs issue, @mroyster provided the right answer - the NEXTAUTH_URL must contain `https://`.

Thanks for pointing into the right direction @oliverlabs.

The One Click Azure Deployment actually creates the App Settings `AZURE_COSMOSEDB_KEY` and `AZURE_COSMOSEDB_URI` (notice the extra E letter), and the code appears to refer the env vars `AZURE_COSMOSDB_KEY` and `AZURE_COSMOSDB_URI` as seen here: https://github.com/microsoft/azurechatgpt/blob/6c76fb9b3239ddd751905755267115f5e9e5b0dd/src/features/common/cosmos.ts#L8C32-L8C50

Might be worth revising the ARM Template and the env var reference here as well: https://github.com/microsoft/azurechatgpt/blob/6c76fb9b3239ddd751905755267115f5e9e5b0dd/README.md?plain=1#L239

**Comment by thivy** [comment]
Please updated the Azure App service application settings that matches the env.local
 
There were few typos and it's fixed

**Comment by aawaheed** [comment]
![image](https://github.com/microsoft/azurechatgpt/assets/6452873/386b1ba6-5a73-4a7c-b185-05bc11d9565e)
I am also facing the same issue of Login loop when running on Azure. With local settings, it works fine using the same ADFS application.

![image](https://github.com/microsoft/azurechatgpt/assets/6452873/743aa1f2-e0f9-4e82-bc43-5c948c8de50d)

**Comment by aawaheed** [comment]
> ![image](https://user-images.githubusercontent.com/6452873/258782779-386b1ba6-5a73-4a7c-b185-05bc11d9565e.png) I am also facing the same issue of Login loop when running on Azure. With local settings, it works fine using the same ADFS application.
> 
> ![image](https://user-images.githubusercontent.com/6452873/258783250-743aa1f2-e0f9-4e82-bc43-5c948c8de50d.png)


I fixed the above issue by adding https:// as mentioned here https://github.com/microsoft/azurechatgpt/issues/62#issuecomment-1666962163
