### ISSUE TITLE
:( Application Error issue

### ISSUE THREAD

**Issue by moruku36** [microsoft/azurechatgpt#39]
I tried deploying from on azure and the app did not start.

<img width="1006" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/12478466/e2c92e89-810d-43be-89cf-cfda50e8d0c3">

I have also created Azure OpenAI in the same region in the same resource group, is there a mistake in the way I created it?

<img width="995" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/12478466/e217b746-728c-44ee-854a-156cfcdeed58">

The diagnostic results are normal.

<img width="728" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/12478466/f7a3650e-94ad-4073-90f9-8573940ceed1">

**Comment by thivy** [comment]
@moruku36 Could you please check all the App settings are setup correctly? Also did the GitHub Actions pass?

**Comment by whymatter** [comment]
Could it be this issue: https://github.com/microsoft/azurechatgpt/issues/35

**Comment by thivy** [comment]
@moruku36 are you still running into this issue?

**Comment by moruku36** [comment]
@thivy sorry for late replay.
My issue was same as issue #35 and solved.
Thank you for help everyone.
