### ISSUE TITLE
Trouble Signing into the Azure application

### ISSUE THREAD

**Issue by Alfonsoaz01** [microsoft/azurechatgpt#42]
Hello, 

First of all, thank you for your contribution I am really looking forward to testing the application :D but I am having some issues when logging into the application. I managed to make the application run in Azure in a webapp:

<img width="516" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/91730802/d9c82847-d9b1-4425-b45b-eee7e6371806">

And I configured both methods of authentication as described in the guide. However, when I clicked in any of them I receive the following error:

<img width="500" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/91730802/0a113a09-97c9-4e07-bb60-7ace967aee7b">

Do you have any ideas why could this happen?

Thank you so much!

**Comment by thivy** [comment]
@Alfonsoaz01 are you still having issues after updating the call back in Azure AD?

**Comment by Alfonsoaz01** [comment]
Hi! thank you for your answer it seemed to work but now I am facing a new error... let me check the configuration again and review it in detail to see what happened.. I think we can close this issue. 

Thank you so much for your help!

**Comment by Alfonsoaz01** [comment]
Closing the issue
