### ISSUE TITLE
Could I bring my Own Data?

### ISSUE THREAD

**Issue by luhgit** [microsoft/azurechatgpt#43]
Hi, Thanks for contributing to this project. I was wondering if I could bring my own data (a bunch of pdfs) to build a chatbot that interacts only based on the knowledge base say Azure Cognitive Search? Currently the Azure OpenAI "bring your own data" feature does not allow much flexibility on the pipeline and the UI is quite minimal so I was wondering if this project also has the "bring your data" feature ready?

**Comment by jasperbaes** [comment]
https://github.com/Azure-Samples/azure-search-openai-demo

Seems like you are looking for this. With azure-search-openai-demo, you can upload your PDF document to a storage acccount. Prompts will exclusively respond with information based on the PDF content. I've used it myself and setup was fairly easy, including adding Azure AD authentication.

**Comment by thivy** [comment]
@luhgit It is the most requested feature, and we are going to add that soon.

**Comment by giuliohome** [comment]
Quick question out of curiosity: I noticed that your code includes environment variables for Azure Search and even code for embeddings and vector similarity. Are these parts currently considered 'dead code' or are they actively used in the app?

See https://github.com/microsoft/azurechatgpt/blob/cafd3c07fe4fb3707329bf5e7ab3a62408fdabae/src/features/chat/chat-data/chat-data-api.ts#L62-L70
and
https://github.com/microsoft/azurechatgpt/blob/cafd3c07fe4fb3707329bf5e7ab3a62408fdabae/src/features/chat/chat-data/chat-data-api.ts#L104-L115
Thanks
Giulio

**Comment by giuliohome** [comment]
I've made the changes mentioned above, configured a Pinecone Vectorstore with a few demo documents, and I can confirm that I was able to integrate my own data using the standard OpenAI embeddings and the Vectorstore similarity search. In essence, this feature has already been released.
