### ISSUE TITLE
MODULE_NOT_FOUND and Container XXX for site XXX has exited, failing site start

### ISSUE THREAD

**Issue by vrodrigues-msft** [microsoft/azurechatgpt#49]
Deployed using "One click Azure deployment"
Authentication configured "Azure AD Authentication provider"

![image](https://github.com/microsoft/azurechatgpt/assets/83491176/4f97702b-9c67-4636-91de-820a1690daab)
![image](https://github.com/microsoft/azurechatgpt/assets/83491176/d3d27f1f-b876-4401-99e8-50cf0359dc96)
![image](https://github.com/microsoft/azurechatgpt/assets/83491176/137910d8-05df-4ba5-83da-f9dc5bad57cc)

**Comment by oliverlabs** [comment]
@vrodrigues-msft, you need to deploy the actuall app into your Web App next. Fork the repo and run the GitHub Actions manually.

**Comment by thivy** [comment]
Thanks @oliverlabs 

Please follow these steps to deploy to Azure App service using GitHub Actions 
https://github.com/microsoft/azurechatgpt#%EF%B8%8F-deploy-to-azure---github-actions
