### ISSUE TITLE
i have few queries

### ISSUE THREAD

**Issue by Govindkumar1986** [microsoft/azurechatgpt#56]
Anyone please advise me the correct answer? 
Question: What are some limitations of Github copilot:
a.it can be difficult to customize based on developers preferences.
b. it can sometimes generate incorrect or buggy code
c. it can only generate code snippets and not entire functions
d. it does not support most of the modern programming languages

**Comment by saadmsft** [comment]
@Govindkumar1986 :  I think this question is bit out of context when it comes to azurechatgpt. I believe a different [forum ](https://github.com/orgs/community/discussions/categories/copilot) would be more suitable :)

**Comment by thivy** [comment]
Thank you @saadmsft for pointing it to the right place. Closing this issue since it's not related.
