### ISSUE TITLE
Possible to change the text limit?

### ISSUE THREAD

**Issue by CrypticKingJoe** [microsoft/azurechatgpt#57]
Is it possible to make this output at least 5k words? or is it capped?

**Comment by maozdemir** [comment]
No idea if it'd work on Azure, but add max_tokens arg here:

https://github.com/microsoft/azurechatgpt/blob/cafd3c07fe4fb3707329bf5e7ab3a62408fdabae/src/features/chat/chat-data/chat-data-api.ts#L30

The official ChatGPT supports 8k tokens, OpenAI's GPT-3.5-TURBO model is 4k tokens and there's a GPT-3.5-TURBO-16K. GPT-4 is 8k and GPT-4-32K is... well... Still worth a shot, for 5k words you need about 8k tokens. I'm just assuming.

**Comment by thivy** [comment]
@CrypticKingJoe as mentioned by @maozdemir  you can set the max tokens. 

  const chatModel = new ChatOpenAI({
    temperature: 0,
    streaming: true,
    maxTokens: 100,
  });
