### ISSUE TITLE
Github OAUTH doesnt redirect

### ISSUE THREAD

**Issue by casrass** [microsoft/azurechatgpt#62]
Once authenticating with Github, it stays on the redirect page and doesn't redirect to /chat.

**Comment by perrytrienekens** [comment]
Hi,

Not 100% sure but seems I have the same with Microsoft 365 as authentication. The OAuth is done, SAML correct and then it stops on this screen and doesn't redirect to /chat:

![LoginStuck](https://github.com/microsoft/azurechatgpt/assets/47396034/2d916daa-390b-43f1-9dc1-5bb7ef1e1f33)

While I check with SAML tracer and that looks all good:
![SAMLTrace](https://github.com/microsoft/azurechatgpt/assets/47396034/65f5eb1f-8c1f-4344-94cf-8d104cfc97b7)

In Azure AD on the Audit Logs I see a successfull authentication, so on that side all seems to work.

How to analyze?
Perry

**Comment by perrytrienekens** [comment]
OK, this one fixed my login issue, the nextauth URL must contain HTTPS

// as for the OPs issue, @mroyster provided the right answer - the NEXTAUTH_URL must contain https://.

**Comment by thivy** [comment]
As
