### ISSUE TITLE
Feature request to allow a user message to be edited

### ISSUE THREAD

**Issue by asimmon** [microsoft/azurechatgpt#64]
In ChatGPT, one can edit a submitted message. This is very useful when you made a mistake and don't want to increase the amount of tokens being sent for a conversation. I believe that ChatGPT preserve the conversation hierarchy as some kind of tree.

I'd like Azure ChatGPT to offer the same user message editing and "message threads" feature.

**Comment by thivy** [comment]
I have added this to the project board https://github.com/orgs/microsoft/projects/909/views/1

**Comment by KeysAU** [comment]
did this feature ever get added?
