### ISSUE TITLE
Feature request to allow the answer generation to be canceled

### ISSUE THREAD

**Issue by asimmon** [microsoft/azurechatgpt#65]
In the original ChatGPT, the user can cancel the AI answer generation for various reasons. Here, in Azure ChatGPT, I see at least two reasons while a user might want to cancel an answer generation:

1. The user don't want to wait until the answer is fully generated.
2. The user want to cancel the generation in order to save on the API usage.

I know that the .NET version of the Azure OpenAI SDK supports cancellation tokens very well with streaming. I haven't looked yet, but I would assume that the same cancellation mechanism would exist for JavaScript.

**Comment by thivy** [comment]
I have added this to the project board https://github.com/orgs/microsoft/projects/909/views/1
