### ISSUE TITLE
Feature request to make the drawer/navbar collapsible and responsive

### ISSUE THREAD

**Issue by asimmon** [microsoft/azurechatgpt#66]
I'd like the sidebar/drawer/navigation menu (my frontend vocabulary is not up-to-date 😅) to be:
* Collapsible
* Collapsed by default on mobile devices

Generally speaking, I'd like the UI to be responsive. Right now on mobile, the sidebar is always open and I have to horizontally scroll in order to read/write messages.

**Comment by thivy** [comment]
I have added this to the project board https://github.com/orgs/microsoft/projects/909/views/1
