### ISSUE TITLE
Just providing some feedback about my experience with Azure ChatGPT

### ISSUE THREAD

**Issue by asimmon** [microsoft/azurechatgpt#68]
So this is not an actual request, feel free to close it.

Just want to say thanks for this project, it works quite well. At some point I wanted to build my own ChatGPT clone (for personal use) in .NET but I'm glad you guys did it for me already. I was able to:

- [Fork it](https://github.com/asimmon/blugpt) 
- Use OpenAI API key instead of Azure OpenAI Service because my Azure subscription is not whitelisted (haven't made the request yet)
- Use Google auth instead of GitHub/Azure AD
- Publish the docker image to Docker Hub
- Deploy it on Azure with Azure CosmosDB free tier + cheap Azure App Service
- Put Cloudflare DNS/TLS on top of it so it's incredibly fast and secure

Works like a charm, only took me ~4 hours hours to do all this. I did open some issues for improvements/feature parity with ChatGPT.

Thanks again.

**Comment by thivy** [comment]
I have added this to the project board https://github.com/orgs/microsoft/projects/909/views/1
