### ISSUE TITLE
Extend README with info about AAD app consent

### ISSUE THREAD

**Issue by murdockcrc** [microsoft/azurechatgpt#74]
Hi

I would like to suggest extending the instructions in the README to include information about the need to grant the EntraID app consent. You will need your AAD admin to grant consent (depending on how your tenant was configured, but these days, it's usual to require an admin to give apps the permissions they request).

I did not find any information about these in the docs (maybe I missed something?)

Thx

**Comment by thivy** [comment]
Good suggestion @murdockcrc, will add this to the backlog
