### ISSUE TITLE
how to disable the Chat Reporting for all users?

### ISSUE THREAD

**Issue by ttbush** [microsoft/azurechatgpt#79]
I found that we can see othe users chat history, how to disable this function?

**Comment by thivy** [comment]
It's not possible to disable as it's one of the core features of Azure ChatGPT. 

However, since the code is modular, you can delete the following two folders 

<img width="280" alt="image" src="https://github.com/microsoft/azurechatgpt/assets/1764153/8fc33cd6-254f-4c0c-9189-be03cc8010a5">
