### ISSUE TITLE
GPT-4 is not set

### ISSUE THREAD

**Issue by giuliohome** [microsoft/azurechatgpt#82]
You're not using the header's tabs.

It would need something like

```ts
  const myModel = props.model === "GPT-4" ? "gpt-4" : "gpt-3.5-turbo"

  const chat = new ChatOpenAI({
    temperature: 0,
    streaming: true,
    modelName:  myModel
  });
```

**Comment by thivy** [comment]
Azure OpenAI Model name is set via the deployment name. Please refer to how LangChain references the model name https://js.langchain.com/docs/modules/model_io/models/llms/integrations/azure 

Based on your suggestion, you can swap the deployment names. I will look to add that as part of a fix

**Comment by giuliohome** [comment]
Yes, I was briefly experimenting with vanilla OpenAI. You're right – you should consider swapping the deployment names. Additionally (at UI level and in Cosmos DB), the history should indicate the model name correctly updated in the header tab. I'm still working on understanding how to accomplish that myself

**Comment by thivy** [comment]
@giuliohome have a look at the new updates. Now the model names are passed correctly and get's saved to the database

**Comment by giuliohome** [comment]
Thank you @thivy , so fast! 🚀  Keep up the good work!

**Comment by giuliohome** [comment]
Just to understand your code changes, it appears that the model names are saved to Cosmos DB, but I can't see them being passed as different deployment names to the Azure OpenAI chat API:

https://github.com/microsoft/azurechatgpt/blob/1b30affa07b8da2f44131211f41c4499b51d0267/src/features/chat/chat-simple/chat-simple-api.ts#L26-L31

As a minor note, which you can ignore for the moment, please be aware that the Azure deployment names might differ from the standard OpenAI `gpt-3.5` and `gpt-4` strings.

**Comment by oliverlabs** [comment]
So how do we add support for gpt4? Do I just update the `AZURE_OPENAI_API_DEPLOYMENT_NAME` variable with the deployment name of my gpt4 model?

**Comment by giuliohome** [comment]
While that would work, what is missing in my opinion is the possibility to dynamically switch from GPT-3.5 to 4 and vice versa via tabs. The current version seems to track those tab selections in the history but without affecting the actual calls to the Chat AI, unfortunately. Not sure if they are going to fix this too.

**Comment by oliverlabs** [comment]
I was able to switch the deployment to GPT4 by replacing the variable, but it would be great to have an option to switch between 3.5 and 4
