### ISSUE TITLE
Document Upload is not working

### ISSUE THREAD

**Issue by error505** [microsoft/azurechatgpt#85]
Hi. First of all thanks for the great app.

Everything works except for the document upload. 
If I try to upload PDF document I always get error 500 Failed to load resources
I have created all services and configured the env.local, unfortunately I am not getting this part to work.
![image](https://github.com/microsoft/azurechatgpt/assets/8121909/8427cd01-73ec-41a0-9dae-c2ef8d677be0)
![image](https://github.com/microsoft/azurechatgpt/assets/8121909/f0ec7517-e56f-48d5-8214-1b583e7be7b3)

**Comment by thivy** [comment]
@error505 could you please check which step the error throws? 
1. Upload 
2. Extract content using document intelligence 
3. Embeddings 
4. Index using Azure Cognitive Search 

All these steps are within this file https://github.com/microsoft/azurechatgpt/blob/main/src/features/chat/chat-services/chat-document-service.ts

**Comment by yazashin** [comment]
@leslyarun I added this setting after pulling main and it works now.
https://github.com/microsoft/azurechatgpt/blob/main/docs/6-chat-over-file.md#azure-openai-embeddings
`AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=`

I hope this is helpful.

**Comment by error505** [comment]
Thanks for your answers, 
Now with the `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=` property and deployment of the text-embeding model in the OpenAI studio it works.
