### ISSUE TITLE
I can see others' chat history

### ISSUE THREAD

**Issue by makeaieasy** [microsoft/azurechatgpt#88]
everyone's chat history is public, how to avoid this?

**Comment by thivy** [comment]
This is by design however you can limit using Azure AD claims with NexAuthJS 
https://next-auth.js.org/configuration/options 
https://learn.microsoft.com/en-us/azure/active-directory/develop/optional-claims

**Comment by patst** [comment]
I was surprised as well to see other users chat history.

We modified the cosmos queries to take into consideration the currently logged in userId

**Comment by oliverlabs** [comment]
@patst, would you consider contributing to this repo with that feature? Could you describe how you did it? Thanks.

**Comment by patst** [comment]
@oliverlabs  sure. I created a PR https://github.com/microsoft/azurechatgpt/pull/97

**Comment by Xtrah** [comment]
Could be nice to be able to toggle this on/off in the code or with an environment variable

**Comment by makeaieasy** [comment]
@patst It works in my fork as well. Many thanks.
