### ISSUE TITLE
Provide Documentation to Deploy to Azure without GitHub Action

### ISSUE THREAD

**Issue by Kirchen99** [microsoft/azurechatgpt#96]
I've noticed that the current documentation focuses solely on deploying ChatGPT to Azure using GitHub Actions. While GitHub Actions is a powerful tool, some users may prefer different deployment methods or may not have access to GitHub for various reasons.

I kindly request that you consider creating documentation that outlines alternative methods for deploying ChatGPT to Azure without relying on GitHub Actions. This would provide more flexibility and accessibility to a wider audience of users who may have different workflows or preferences.

**Comment by oliverlabs** [comment]
@Kirchen99, it's fairly simple to deploy the app manually.

1. Do an `npm install` and `npm run build` like so:
```bash
cd ./src
npm install
npm run build --if-present
cd ..
```

2. Copy standalone into the root
```bash
cp -R ./src/.next/standalone ./site-deploy
```

3. Copy static into the .next folder
```bash
cp -R ./src/.next/static ./site-deploy/.next/static
```

4. Copy Public folder
```bash
cp -R ./src/public ./site-deploy/public
```

5. Create a zip of your Next application
```bash
cd ./site-deploy
zip Nextjs-site.zip ./* .next -qr 
```

6. Deploy to a Web App via REST API cURL command or using Azure CLI
```bash
az functionapp deployment source config-zip -g <resource_group> -n \
<app_name> --src Nextjs-site.zip
```
or
```bash
curl -X POST \
    --data-binary "@Nextjs-site.zip" \
    -H "Authorization: Bearer <access_token>" \
    "https://<app_name>.scm.azurewebsites.net/api/zipdeploy"
```

Hope this helps.

**Comment by Kirchen99** [comment]
Thank you for the quick response!

After successfully deploying my application to Azure, I encountered the following error:

```
AADSTS50011: The redirect URI 'https://<app_name>.azurewebsites.net/.auth/login/aad/callback' specified in the request does not match the redirect URIs configured for the application 
```

And I checked my "Redirect URI" in the "App registrations": 

before:

```
https://<app_name>.azurewebsites.net/api/auth/callback/azure-ad
```

after:

```
https://<app_name>.azurewebsites.net/.auth/login/aad/callback
```

With this adjustment, I attempted to log in again at https://<app_name>.azurewebsites.net, and this time, the login process succeeded. However, I'm now encountering an "Internal Server Error." I see nothing in the application logs. Could you kindly assist in identifying any further steps or configurations I may be missing? Your guidance is greatly appreciated.

**Comment by Kirchen99** [comment]
I ran into this problem because I added an identity provider to the Authentication option of the Azure App. After I removed the identity provider, it works. Thanks again for the help.

**Comment by jupiter19914** [comment]
@oliverlabs in your instructions to deploy manually why is the last step using "az functionapp deployment" instead of "az webapp deployment"?

**Comment by oliverlabs** [comment]
@jupiter19914, you are correct. It should be `az webapp`. I will fix the command above.
